// <auto-generated />
namespace WOTAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedGUIDAndAnnotationToNation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedGUIDAndAnnotationToNation));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281703523_AddedGUIDAndAnnotationToNation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
